In [1]:
from py_vollib_vectorized import vectorized_black_scholes_merton
import plotly as py
from plotly.offline import init_notebook_mode
import plotly.graph_objs as go
from crypto_spider.tushare_ivSurface import main, im_surface
import numpy as np

init_notebook_mode(connected = True)

In [2]:
'''
df structure:

##     TTM Strike market  imp_vol
## 1  0.07    850   0.45 0.194722
## 2  0.07    875   0.60 0.252699
## 3  0.07    900   0.15 0.245498
## 9  0.07    400 370.25 0.755884
## 10 0.07    425 345.35 0.812275
## 12 0.07    450 320.55 0.826739
'''
df = main('20220715')
df = df.reset_index()

In [3]:
dt = 1/252
dk = 1.5
local_vol = np.zeros([1,len(df)])

In [18]:
dc_by_dt = (vectorized_black_scholes_merton('c',df.s,df.k,df.t + dt,0,df.iv,0,return_as='array') - vectorized_black_scholes_merton('c',df.s,df.k,df.t,0,df.iv,0,return_as='array'))/dt

dc_by_dk = (vectorized_black_scholes_merton('c',df.s,df.k + dk,df.t,0,df.iv,0,return_as='array') - vectorized_black_scholes_merton('c',df.s,df.k,df.t,0,df.iv,0,return_as='array'))/dk

d2c_by_dk2 = (vectorized_black_scholes_merton('c',df.s,df.k + dk,df.t,0,df.iv,0,return_as='array')  - 2 * vectorized_black_scholes_merton('c',df.s,df.k,df.t,0,df.iv,0,return_as='array') + vectorized_black_scholes_merton('c',df.s,df.k - dk,df.t,0,df.iv,0,return_as='array'))/(dk **2)

In [19]:
for i in range(len(df)):
    local_vol[0,i] = np.sqrt((dc_by_dt[i] + df.loc[i,'r'] * df.loc[i,'c'] - (df.loc[i,'r'] - df.loc[i,'q']) * (df.loc[i,'c'] - df.loc[i,'k'] * dc_by_dk[i]))/(0.5 * df.loc[i,'k'] **2 * d2c_by_dk2[i]))

In [20]:
local_vol[0]

array([0.34018618, 0.29766681, 0.33469361, 0.48267592, 0.19844859,
       0.14731676, 0.33062908, 0.19447704, 0.344581  , 0.27850224,
       0.32286164, 0.27606413, 0.33706464, 0.2223859 , 0.28327745,
       0.27697718, 0.32250743, 0.28868356, 0.39191111, 0.21304113,
       0.37501085, 0.47346034, 0.2659892 , 0.27197137, 0.22623119,
       0.17938656, 0.17293005, 0.17755341, 0.2132413 , 0.22087888,
       0.24580163, 0.30956156, 0.41459804, 0.25001553, 0.24014431,
       0.27719998, 0.18717376, 0.32146993, 0.16386664, 0.44465177,
       0.19481442, 0.2279597 , 0.25825333, 0.28475144, 0.36754051,
       0.28114164, 0.16650501, 0.3765537 , 0.32872165, 0.25963762,
       0.31285457, 0.26800145, 0.28961456, 0.35503263, 0.27461469,
       0.36355468, 0.28787498, 0.28685155, 0.2566785 , 0.34861259,
       0.33866195, 0.29655152, 0.33466646, 0.48241245, 0.20035829,
       0.16123987, 0.33024296, 0.19608498, 0.34338339, 0.27860363,
       0.32314977, 0.27634891, 0.33681181, 0.21503504, 0.28299

In [5]:
dc_by_dt.loc[0,0]

IndexingError: Too many indexers

In [6]:
vectorized_black_scholes_merton('c',df.c,df.k,df.t + dt,0,df.iv,0,return_as='array')

array([0.00000000e+000, 7.53766313e-104, 3.29271123e-235, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 1.13204000e-174, 7.58083008e-253,
       4.45899641e-291, 2.08163015e-085, 2.85038057e-316, 5.55922141e-112,
       5.88729713e-200, 0.00000000e+000, 3.05804821e-052, 0.00000000e+000,
       4.24161883e-147, 9.71796122e-074, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.87916495e-036, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.96161065e-214, 0.00000000e+000, 2.27667426e-162, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 2.37852705e-059, 2.47034541e-044,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.14471775e-192, 0.00000000e+000, 3.63886037e-093,
       0.00000000e+000, 2.39308175e-101, 0.00000000e+000, 0.00000000e+000,
       2.21341822e-282, 2.20176130e-138, 8.95769577e-124, 0.00000000e+000,
       2.33458744e-067, 0

In [17]:
vectorized_black_scholes_merton('c',df.s,df.k,df.t,df.r,df.iv,df.q,return_as='array')

array([1.75800531e-01, 3.00000515e-01, 1.24492488e-01, 5.20028682e-02,
       4.29934674e-03, 2.99196561e-04, 1.83593927e-01, 2.22021527e-02,
       1.94398319e-01, 3.46302664e-01, 7.79004597e-02, 1.18999423e-01,
       1.52296945e-01, 2.71999657e-01, 3.06301571e-01, 3.54997532e-02,
       2.19998526e-01, 2.11999420e-01, 1.29226082e-01, 1.25006080e-02,
       1.19600617e-01, 2.83977225e-02, 4.17998708e-01, 2.22600985e-01,
       6.99904685e-03, 5.90170260e-03, 5.01190776e-04, 2.80071351e-03,
       3.25997791e-02, 1.20034473e-03, 6.24990715e-02, 6.05137580e-02,
       1.32005805e-02, 2.13962163e-02, 4.38000484e-01, 3.48616428e-01,
       7.60034532e-03, 2.76004869e-02, 3.24099315e-01, 8.85995607e-02,
       7.66134851e-04, 4.42031511e-02, 2.09866856e-03, 1.58477037e-01,
       6.25995871e-02, 1.38600346e-01, 2.10061514e-03, 8.90051607e-02,
       9.77012109e-02, 8.67978815e-02, 2.58001676e-01, 1.30992938e-02,
       2.37298252e-01, 4.35947722e-02, 3.77399434e-01, 1.53401557e-01,
      